### PR TITLE
Bump sbt version and all dependencies. Minor changes to make it build.

### PR DESCRIPTION
**Pull request by torkjel**
Removed the sbt-dependency-graph plugin, as I can't see it being used.

### CODE REVIEW

**Comment by laughedelic** [comment]
@torkjel @pcejrowski let's merge this and enable Scala Steward?

**Review by pcejrowski — APPROVED** [review]
Nice!

**Comment by laughedelic** [comment]
@pcejrowski I guess, it's now because problematic to release it, since Bintray has closed.

**Comment by pcejrowski** [comment]
@laughedelic yes, let's publish it internally to test this out, and we can hopefully find some time to create Sonatype OSS shipment later.

**Pull request merged**
